# Generated by Django 3.2.12 on 2022-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_advice_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст совета'),
        ),
        migrations.AddField(
            model_name='advice',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст совета'),
        ),
        migrations.AddField(
            model_name='advice',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advice',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advice',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
    ]
